#!/usr/bin/env python3
"""Announce newly published posts on Bluesky.

Reads the built RSS feed (public/index.xml), compares it against the list of
things already announced, and posts anything new.

Two properties make this safe to run on every push:

  * Drafts never appear. The feed is generated by a production `hugo` build,
    which excludes `draft = true` pages, so a draft cannot leak out. About and
    CV are excluded too, via `[_build] list = false` in their front matter.

  * Editing a published post does not re-announce it. Every announced URL is
    recorded in the state file, and anything already there is skipped. Without
    this, the fifteen commits it took to edit one post would have produced
    fifteen Bluesky posts.

Set DRY_RUN=1 to print what would be posted without touching the network.
"""

import json
import os
import re
import sys
import urllib.request
import urllib.error
from html import unescape
from pathlib import Path

FEED = Path("public/index.xml")
STATE = Path(".github/announced.json")
PDS = "https://bsky.social"
# Bluesky's limit is 300 graphemes; leave room for the URL and a newline.
MAX_TEXT = 280


def feed_items(xml: str):
    """Every item in the feed, newest first, as (title, link, description)."""
    out = []
    for block in re.findall(r"<item>(.*?)</item>", xml, re.S):
        def field(name):
            m = re.search(rf"<{name}>(.*?)</{name}>", block, re.S)
            return unescape(m.group(1)).strip() if m else ""
        link = field("link")
        if link:
            out.append((field("title"), link, field("description")))
    return out


def compose(title: str, link: str, description: str) -> str:
    """Post text: title, then subtitle if it fits, then the URL on its own line."""
    body = title
    if description and len(title) + len(description) + 2 <= MAX_TEXT:
        body = f"{title}\n{description}"
    if len(body) > MAX_TEXT:
        body = body[: MAX_TEXT - 1].rstrip() + "…"
    return f"{body}\n\n{link}"


def link_facet(text: str, link: str):
    """Make the URL a real clickable link. Byte offsets, not character ones."""
    raw = text.encode("utf-8")
    start = raw.rfind(link.encode("utf-8"))
    if start < 0:
        return []
    return [{
        "index": {"byteStart": start, "byteEnd": start + len(link.encode("utf-8"))},
        "features": [{"$type": "app.bsky.richtext.facet#link", "uri": link}],
    }]


def api(url: str, payload=None, token=None):
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, headers=headers)
    try:
        with urllib.request.urlopen(req) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        sys.exit(f"Bluesky API error {e.code} at {url}: {e.read().decode()[:400]}")


def main():
    dry_run = os.environ.get("DRY_RUN") == "1"

    if not FEED.exists():
        sys.exit(f"{FEED} not found — run `hugo` before this script.")

    announced = set(json.loads(STATE.read_text())) if STATE.exists() else set()
    items = feed_items(FEED.read_text())
    new = [i for i in items if i[1] not in announced]

    if not new:
        print("Nothing new to announce.")
        return

    # Oldest first, so a batch reads in publication order.
    new.reverse()
    print(f"{len(new)} new post(s) to announce:")

    token = did = None
    if not dry_run:
        handle = os.environ["BLUESKY_HANDLE"]
        session = api(f"{PDS}/xrpc/com.atproto.server.createSession",
                      {"identifier": handle,
                       "password": os.environ["BLUESKY_APP_PASSWORD"]})
        token, did = session["accessJwt"], session["did"]

    for title, link, description in new:
        text = compose(title, link, description)
        print("\n--- would post ---" if dry_run else "\n--- posting ---")
        print(text)

        if dry_run:
            continue

        api(f"{PDS}/xrpc/com.atproto.repo.createRecord", {
            "repo": did,
            "collection": "app.bsky.feed.post",
            "record": {
                "$type": "app.bsky.feed.post",
                "text": text,
                "facets": link_facet(text, link),
                "createdAt": __import__("datetime").datetime.now(
                    __import__("datetime").timezone.utc
                ).isoformat().replace("+00:00", "Z"),
                "embed": {
                    "$type": "app.bsky.embed.external",
                    "external": {"uri": link, "title": title,
                                 "description": description or ""},
                },
            },
        }, token=token)
        announced.add(link)

    if dry_run:
        print("\nDry run: nothing sent, state file untouched.")
        return

    STATE.parent.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(sorted(announced), indent=2) + "\n")
    print(f"\nState written: {len(announced)} announced URL(s).")


if __name__ == "__main__":
    main()
